#!/usr/bin/env python3
"""Validate a flat exported DojoFlow-VLA checkpoint without loading 4.5B weights."""

from __future__ import annotations

import argparse
import hashlib
import json
import pickle
from pathlib import Path

import numpy as np


EXPECTED_NORM_SHA256 = (
    "8ab506debab53fd20b0235a0e025f10daf3973d5a9ab8111e0f67a27a331e319"
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("checkpoint", type=Path)
    args = parser.parse_args()

    root = args.checkpoint.expanduser().resolve()
    config_path = root / "config.json"
    norm_path = root / "norm_stats.pkl"
    tokenizer_path = root / "tokenizer.json"
    weights = sorted(root.glob("*.safetensors")) + sorted(root.glob("*.bin"))

    assert config_path.is_file(), f"missing {config_path}"
    assert tokenizer_path.is_file(), f"missing {tokenizer_path}"
    assert norm_path.is_file(), f"missing {norm_path}"
    assert weights, "no model weights found"
    assert all(path.stat().st_size > 0 for path in weights), "empty weight file"

    config = json.loads(config_path.read_text(encoding="utf-8"))
    assert config.get("n_action_steps") == 25
    assert config.get("use_video_encoder") is True
    assert config.get("vlm_config_dict"), "checkpoint is not self-contained"

    norm_hash = sha256(norm_path)
    assert norm_hash == EXPECTED_NORM_SHA256, (
        f"unexpected norm stats hash: {norm_hash}"
    )

    # The pickle is generated by the trusted upstream preprocessing script.
    with norm_path.open("rb") as stream:
        stats = pickle.load(stream)

    expected_shapes = {
        "qpos_mean": (20,),
        "qpos_std": (20,),
        "action_mean": (25, 20),
        "action_std": (25, 20),
        "action_mean_abs": (25, 20),
        "action_std_abs": (25, 20),
    }
    for key, expected in expected_shapes.items():
        array = np.asarray(stats[key])
        assert array.shape == expected, (key, array.shape, expected)
        assert np.isfinite(array).all(), f"{key} contains NaN/Inf"
        if key.endswith("_std"):
            assert np.all(array > 0), f"{key} contains non-positive std"

    print(f"checkpoint: {root}")
    print(f"weights: {len(weights)} file(s), {sum(p.stat().st_size for p in weights)} bytes")
    print(f"norm_stats_sha256: {norm_hash}")
    print("CHECKPOINT_VALIDATION: PASS")


if __name__ == "__main__":
    main()
